name: Python Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install testing dependencies if the file exists
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi


      - name: Run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -v